@extends('layouts.app')

@section('content')
<div class="row text-dark">
    <div class="col-12 mb-4">
        <div class="card bg-white border shadow-sm p-4">
            <h4 class="font-weight-bold mb-1">Payment Links</h4>
            <p class="text-muted mb-0">Staff generated EMI payment links and their current status.</p>
        </div>
    </div>

    <div class="col-12 mb-4">
        <div class="card bg-white border shadow-sm p-4">
            <form method="GET" class="row">
                <div class="col-md-4 form-group">
                    <label class="font-weight-bold">Search</label>
                    <input type="text" name="search" value="{{ request('search') }}" class="form-control" placeholder="Transaction, booking, customer">
                </div>
                <div class="col-md-3 form-group">
                    <label class="font-weight-bold">Status</label>
                    <select name="status" class="form-control">
                        <option value="">All</option>
                        @foreach(['Pending', 'Paid', 'Expired', 'Failed', 'Cancelled'] as $status)
                            <option value="{{ $status }}" @selected(request('status') === $status)>{{ $status }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-3 form-group d-flex align-items-end">
                    <button class="btn btn-primary btn-sm mr-2">Filter</button>
                    <a href="{{ route('payment-links.index') }}" class="btn btn-light btn-sm">Reset</a>
                </div>
            </form>
        </div>
    </div>

    <div class="col-12">
        <div class="card bg-white border shadow-sm p-4">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Transaction Number</th>
                            <th>Booking</th>
                            <th>Customer</th>
                            <th>Payment Type</th>
                            <th>EMI Number</th>
                            <th>Amount</th>
                            <th>Generated By</th>
                            <th>Generated At</th>
                            <th>Expiry</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($links as $link)
                            <tr>
                                <td class="font-weight-bold text-primary">{{ $link->transaction_number }}</td>
                                <td>{{ $link->booking->booking_number ?? 'N/A' }}</td>
                                <td>{{ $link->booking->customer->name ?? $link->customer->name ?? 'N/A' }}</td>
                                <td>{{ strtoupper($link->payment_type) }}</td>
                                <td>#{{ $link->emiSchedule->installment_number ?? 'N/A' }}</td>
                                <td class="font-weight-bold text-success">₹{{ number_format($link->amount, 2) }}</td>
                                <td>{{ $link->generatedBy->name ?? 'System' }}</td>
                                <td>{{ $link->generated_at?->format('d M Y H:i') ?? $link->created_at?->format('d M Y H:i') }}</td>
                                <td>{{ $link->expires_at?->format('d M Y H:i') ?? 'N/A' }}</td>
                                <td><span class="badge badge-secondary">{{ $link->link_status ?? $link->payment_status }}</span></td>
                                <td class="text-nowrap">
                                    <a href="{{ route('payment-links.show', $link) }}" class="btn btn-sm btn-outline-primary">View</a>
                                    <form action="{{ route('payment-links.copy', $link) }}" method="POST" class="d-inline">
                                        @csrf
                                        <button class="btn btn-sm btn-outline-info">Copy Link</button>
                                    </form>
                                    @if($link->payment_status !== 'Success')
                                        <form action="{{ route('payment-links.regenerate', $link) }}" method="POST" class="d-inline">
                                            @csrf
                                            <button class="btn btn-sm btn-outline-warning">Regenerate</button>
                                        </form>
                                    @endif
                                </td>
                            </tr>
                        @empty
                            <tr><td colspan="11" class="text-center text-muted py-4">No payment links found.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <div class="mt-3">{{ $links->links() }}</div>
        </div>
    </div>
</div>
@endsection
