@extends('layouts.app')

@section('content')
<div class="row text-dark">
    <div class="col-12 mb-4">
        <div class="card bg-white border shadow-sm p-4">
            <div class="d-flex justify-content-between flex-wrap">
                <div>
                    <h4 class="font-weight-bold mb-1">Payment Link {{ $paymentLink->transaction_number }}</h4>
                    <p class="text-muted mb-0">{{ $paymentLink->booking->booking_number ?? 'N/A' }} · EMI #{{ $paymentLink->emiSchedule->installment_number ?? 'N/A' }}</p>
                </div>
                <a href="{{ route('payment-links.index') }}" class="btn btn-light btn-sm">Back</a>
            </div>
        </div>
    </div>

    <div class="col-lg-7 mb-4">
        <div class="card bg-white border shadow-sm p-4 h-100">
            <h5 class="font-weight-bold mb-3">Details</h5>
            <div class="mb-2"><strong>Booking:</strong> {{ $paymentLink->booking->booking_number ?? 'N/A' }}</div>
            <div class="mb-2"><strong>Customer:</strong> {{ $paymentLink->booking->customer->name ?? 'N/A' }}</div>
            <div class="mb-2"><strong>EMI Number:</strong> #{{ $paymentLink->emiSchedule->installment_number ?? 'N/A' }}</div>
            <div class="mb-2"><strong>Amount:</strong> ₹{{ number_format($paymentLink->amount, 2) }}</div>
            <div class="mb-2"><strong>Gateway:</strong> {{ ucfirst($paymentLink->gateway) }}</div>
            <div class="mb-2"><strong>Generated By:</strong> {{ $paymentLink->generatedBy->name ?? 'System' }}</div>
            <div class="mb-2"><strong>Generated At:</strong> {{ $paymentLink->generated_at?->format('d M Y H:i') ?? 'N/A' }}</div>
            <div class="mb-2"><strong>Expiry:</strong> {{ $paymentLink->expires_at?->format('d M Y H:i') ?? 'N/A' }}</div>
            <div class="mb-2"><strong>Status:</strong> {{ $paymentLink->link_status ?? $paymentLink->payment_status }}</div>
            <div class="mb-0"><strong>Payment URL:</strong> <span class="text-break">{{ $paymentLink->payment_url }}</span></div>
        </div>
    </div>

    <div class="col-lg-5 mb-4">
        <div class="card bg-white border shadow-sm p-4 h-100">
            <h5 class="font-weight-bold mb-3">Timeline</h5>
            @forelse($timeline as $item)
                <div class="border-bottom pb-2 mb-2">
                    <div class="font-weight-bold">{{ \Illuminate\Support\Str::headline($item->action_type) }}</div>
                    <div class="small text-muted">{{ $item->created_at?->format('d M Y H:i') }}</div>
                    <div class="small">{{ $item->description }}</div>
                </div>
            @empty
                <p class="text-muted mb-0">No timeline entries found.</p>
            @endforelse
        </div>
    </div>
</div>
@endsection
